# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='periods',
            field=models.ManyToManyField(to='agreement.Period'),
        ),
    ]
