# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0002_agreement_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='period',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
