# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0004_auto_20171126_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='name',
        ),
        migrations.RemoveField(
            model_name='period',
            name='name',
        ),
        migrations.AlterField(
            model_name='agreement',
            name='periods',
            field=models.ManyToManyField(to='agreement.Period'),
        ),
    ]
